name: documentation

on:
  push:
    branches: [ stable ]

jobs:

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.10

    - name: Build
      run: |
        sudo apt-get install graphviz pandoc
        python -m pip install --upgrade pip
        pip install .[dev]
        make -C docs html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: docs/build/html